### ISSUE TITLE
Missing ILO 6 integration / Unknown ILO Model

### ISSUE THREAD

**Issue by Wintermute2k6** [NETWAYS/check_hp_firmware#78]
As with the latest ILO 6 from HPE ..

It seems to hit HP Hardware with the firmware >= firmware=52.22.3-4650

Output is = status: other
and [CRITICAL] unknown Ilo model

**Comment by Wintermute2k6** [comment]
refNC/800641

**Comment by martialblog** [comment]
Had a closer look at the internal ticket. My thoughts so far:

Unknown iLO versions are detected by the Plugin and are reported as "ok since not affected by known stull".

The error received with the v1.3.1 is: ` error establishing connection to host: dial udp :0->10.redacted:161: i/o timeout (*fmt.wrapError)`

Also the boolean `--ilo` flag is used with an argument?

Right now, I assume that there is actually a connection issue and the older v1.2.0 version didn't report that. 

Besides that. Yes, we could add iLO 6 support. But we need to know the `CpqSm2CntlrModel .1.3.6.1.4.1.232.9.2.2.21` from the iLOs SNMP response.

Given the current list, I assume it's `pciIntegratedLightsOutRemoteInsight6`. But really no idea.

```
	9:  "pciIntegratedLightsOutRemoteInsight3", // Integrated Lights-Out 3 Edition
	10: "pciIntegratedLightsOutRemoteInsight4", // Integrated Lights-Out 4 Edition
	11: "pciIntegratedLightsOutRemoteInsight5", // Integrated Lights-Out 5 Edition
```

Once we know that, we can add the current Firmware version (iLO 6 v1.56) to this list:

```
var FixedVersionMap = map[string]PlatformInfo{
	"pciIntegratedLightsOutRemoteInsight3": {"3", "1.93"},
	"pciIntegratedLightsOutRemoteInsight4": {"4", "2.75"},
	"pciIntegratedLightsOutRemoteInsight5": {"5", "2.18"},
}
```
